// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


var List$prime = { };

function length(param) {
  if (param) {
    return 1 + length(param[0][1]) | 0;
  } else {
    return 0;
  }
}

var List = {
  length: length
};

exports.List$prime = List$prime;
exports.List = List;
/* No side effect */
