// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


function length(param) {
  if (param) {
    return 1 + length(param[1]) | 0;
  } else {
    return 0;
  }
}

function pop(param) {
  return param[1];
}

function push(l, v) {
  if (l) {
    return /* :: */[
            v,
            l
          ];
  } else {
    return /* :: */[
            v,
            /* [] */0
          ];
  }
}

exports.length = length;
exports.pop = pop;
exports.push = push;
/* No side effect */
