// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


function inc(n) {
  return /* Succ */[n];
}

function dec(param) {
  return param[0];
}

function isEqual(_i, _j) {
  while(true) {
    var j = _j;
    var i = _i;
    if (i) {
      if (j) {
        _j = j[0];
        _i = i[0];
        continue ;
      } else {
        return false;
      }
    } else if (j) {
      return false;
    } else {
      return true;
    }
  };
}

function $$eval(param) {
  if (param) {
    return 1 + $$eval(param[0]) | 0;
  } else {
    return 0;
  }
}

var two = /* Succ */[/* Succ */[/* Zero */0]];

var three = /* Succ */[two];

var one = /* Succ */[/* Zero */0];

exports.inc = inc;
exports.dec = dec;
exports.isEqual = isEqual;
exports.$$eval = $$eval;
exports.one = one;
exports.two = two;
exports.three = three;
/* No side effect */
