// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


function id(x) {
  return x;
}

function id$prime(x) {
  return x;
}

function id$prime$prime$prime(x) {
  return x;
}

function lower(_x) {
  return true;
}

function upper(_x) {
  return true;
}

function even1(x) {
  return x[1] % 2 === 0;
}

function even2(x) {
  return x[1].length % 2 === 0;
}

function even(x) {
  if (even1(x)) {
    return even2(x);
  } else {
    return false;
  }
}

function f(x) {
  return x;
}

function f$prime(x) {
  return x;
}

function f$prime$prime(x) {
  return x;
}

function f$prime$prime$prime(x) {
  return x;
}

function f$prime$prime$prime$prime(x) {
  return x;
}

function id1(x) {
  return x;
}

function id2(x) {
  return x;
}

var makeIntBool = /* `Int */[
  3654863,
  /* tuple */[
    123,
    true
  ]
];

var red = /* Red */4100401;

var rg = /* Red */4100401;

var rg$prime = /* Red */4100401;

var rg$prime$prime = /* Red */4100401;

exports.makeIntBool = makeIntBool;
exports.red = red;
exports.id = id;
exports.rg = rg;
exports.rg$prime = rg$prime;
exports.rg$prime$prime = rg$prime$prime;
exports.id$prime = id$prime;
exports.id$prime$prime$prime = id$prime$prime$prime;
exports.lower = lower;
exports.upper = upper;
exports.even1 = even1;
exports.even2 = even2;
exports.even = even;
exports.f = f;
exports.f$prime = f$prime;
exports.f$prime$prime = f$prime$prime;
exports.f$prime$prime$prime = f$prime$prime$prime;
exports.f$prime$prime$prime$prime = f$prime$prime$prime$prime;
exports.id1 = id1;
exports.id2 = id2;
/* No side effect */
