// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var HList$ReasonmlConcepts = require("./gadt/HList.bs.js");
var Primitive$ReasonmlConcepts = require("./gadt/Primitive.bs.js");

console.log("Hello, BuckleScript and Reason!");

console.log("\n GADTs Usage");

console.log("1. EVAL");

console.log(Primitive$ReasonmlConcepts.$$eval(/* Int */Block.__(0, [64])));

console.log(Primitive$ReasonmlConcepts.$$eval(/* String */Block.__(1, ["hellpo"])));

console.log(Primitive$ReasonmlConcepts.$$eval(/* Float */Block.__(2, [43.0234234])));

console.log(Primitive$ReasonmlConcepts.$$eval(/* Bool */Block.__(3, [false])));

console.log("1. HLIST");

console.log(/* :: */[/* tuple */[
        1,
        /* :: */[/* tuple */[
            2,
            /* :: */[/* tuple */[
                3,
                /* :: */[/* tuple */[
                    4,
                    /* [] */0
                  ]]
              ]]
          ]]
      ]]);

console.log(/* :: */[/* tuple */[
        "1",
        /* :: */[/* tuple */[
            1,
            /* :: */[/* tuple */[
                false,
                /* :: */[/* tuple */[
                    4.645,
                    /* [] */0
                  ]]
              ]]
          ]]
      ]]);

console.log(HList$ReasonmlConcepts.List.length(/* :: */[/* tuple */[
            "1",
            /* :: */[/* tuple */[
                1,
                /* :: */[/* tuple */[
                    false,
                    /* :: */[/* tuple */[
                        4.645,
                        /* [] */0
                      ]]
                  ]]
              ]]
          ]]));

/*  Not a pure module */
